In [1]:
import numpy as np

C:\Users\Leo\AppData\Roaming\Python\Python37\site-packages\numpy\_distributor_init.py:32: UserWarning: loaded more than 1 DLL from .libs:
C:\Users\Leo\AppData\Roaming\Python\Python37\site-packages\numpy\.libs\libopenblas.GK7GX5KEQ4F6UYO3P26ULGBQYHGQO7J4.gfortran-win_amd64.dll
C:\Users\Leo\AppData\Roaming\Python\Python37\site-packages\numpy\.libs\libopenblas.WCDJNK7YVMPZQ2ME2ZZHJJRJ3JIKNDB7.gfortran-win_amd64.dll
  stacklevel=1)


1. Write a NumPy program to test whether none of the elements of a given array is zero. 

In [2]:
x = [0, 1, 2, 3, 4]
np.all(x) 
#Test whether all array elements along a given axis evaluate to True.

False

Write a NumPy program to test a given array element-wise for finiteness

In [3]:
a = np.array([1, 0, np.nan, np.inf])
np.isfinite(a)
#Test element-wise for finiteness (not infinity or not Not a Number)

array([ True,  True, False, False])

Write a NumPy program to test element-wise for positive or negative infinity.

In [4]:
np.isinf(a)

array([False, False, False,  True])

Write a NumPy program to test element-wise for NaN of a given array.

In [5]:
np.isnan(a)

array([False, False,  True, False])

<h2>NumPy: Array Object Exercises</h2>

Write a NumPy program to create a 3x3 matrix with values ranging from 2 to 10.

In [12]:
a = np.arange(2,11)
print(a)
a = a.reshape(3,3)
print(a)

[ 2  3  4  5  6  7  8  9 10]
[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


Write a NumPy program to create a null vector of size 10 and update sixth value to 11

In [21]:
a = np.zeros(10)
print(a)

a[5] = 11
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[ 0.  0.  0.  0.  0. 11.  0.  0.  0.  0.]


Write a NumPy program to create an array with values ranging from 12 to 38

In [23]:
a = np.arange(12, 38)
print(a)

[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]


Write a NumPy program to convert an array to a float type. 

In [26]:
a = [1,2,3,4]

a = a.astype(float)
print(a)

AttributeError: 'list' object has no attribute 'astype'

In [28]:
a = np.array(a).astype(float)
print(a)

[1. 2. 3. 4.]


Write a NumPy program to create a 2d array with 1 on the border and 0 inside. 

In [39]:
a = np.ones((5,5))
print("before\n", a)

print("-"*30)
a[1:-1, 1:-1] = 0
print("after \n", a)

before
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
------------------------------
after 
 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


Write a NumPy program to add a border (filled with 0's) around an existing array. 

In [40]:
a = np.pad(a, pad_width=1, mode='constant', constant_values=0)
#pad add board for the array
a

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

Write a NumPy program to create an empty and a full array.

In [41]:
x = np.empty((3,4))
print(x)
# Create a full array
y = np.full((3,3),6)
print(y)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[6 6 6]
 [6 6 6]
 [6 6 6]]


In [45]:
np.empty((3,2))
#Return a new array of given shape and type, without initializing entries.

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

Write a NumPy program to convert the values of Centigrade degrees into Fahrenheit degrees. Centigrade values are stored into a NumPy array.

In [63]:
F = np.random.randint(30, size = (10))
F

array([25, 20,  6,  1, 23, 13, 21, 27,  0, 27])

In [64]:
C = 5*F/9 - 5*32/9
C

array([ -3.88888889,  -6.66666667, -14.44444444, -17.22222222,
        -5.        , -10.55555556,  -6.11111111,  -2.77777778,
       -17.77777778,  -2.77777778])

Write a NumPy program to find common values between two arrays. 

In [65]:
import numpy as np
array1 = np.array([0, 10, 20, 40, 60])
print("Array1: ",array1)
array2 = [0, 40]
print("Array2: ",array2)
print("Compare each element of array1 and array2")
print(np.in1d(array1, array2))

Array1:  [ 0 10 20 40 60]
Array2:  [0, 40]
Compare each element of array1 and array2
[ True False False  True False]


Write a NumPy program to find common values between two arrays. 

In [67]:
import numpy as np
array1 = np.array([0, 10, 20, 40, 60])
print("Array1: ",array1)
array2 = [0, 40]
print("Array2: ",array2)
print("Common value:", np.intersect1d(array1, array2))

Array1:  [ 0 10 20 40 60]
Array2:  [0, 40]
Common value: [ 0 40]


Write a NumPy program to find the indices of the maximum and minimum values along the given axis of an array.

In [72]:
a = np.arange(7)
minV = np.argmin(a)
print(minV)
maxV = np.argmax(a)
print(maxV)

0
6


Write a NumPy program compare two given arrays. 

In [75]:
a = np.array([1, 2])
b = np.array([4, 5])
print(a>b)
print(a<b)

[False False]
[ True  True]


Write a NumPy program to sort an along the first, last axis of an array. 

In [88]:
a = np.array([[4, 6],[2, 1]])
print("original array:\n", a)

x = np.sort(a, axis = 0)
print("sort by first axis:\n", x)

y = np.sort(a, axis = 1)
print("sort by last axis:\n", y)

original array:
 [[4 6]
 [2 1]]
sort by first axis:
 [[2 1]
 [4 6]]
sort by last axis:
 [[4 6]
 [1 2]]
